##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#   2024-04-27 - Added env file inclusion. 
#                Added way to overide: build directory, target name and optimisation.
#                Added GCC_PATH by env file to not make the makefile machine dependent.
#                Currently folder structure in build directory is preserved
#                Switching of debug/release build output folder now happens based on debug flag
#   2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# Environment Variables
######################################
# Imports the environment file in which the compiler and other tooling is set
# for the build machine.
# This can also be used to overwrite some makefile variables
file_exists = $(or $(and $(wildcard $(1)),1),0)
ifeq ($(call file_exists,.stm32env),1)
  include .stm32env
endif

######################################
# Target
######################################
# This is the name of the embedded target which will be build
# The final file name will also have debug or release appended to it.
TARGET ?= TEv2

#######################################
# Build directories
#######################################
# Build path can be overwritten when calling make or setting the environment variable
# in .stm32env

BUILD_DIRECTORY ?= build


######################################
# Optimization
######################################
# Optimization is switched based upon the DEBUG variable. If set to 1
# it will be build in debug mode with the Og optimization flag (optimized for debugging).
# If set to 0 (false) then by default the variable is used in the configuration yaml
# This can also be overwritten using the environment variable or by overwriting it
# by calling make with the OPTIMIZATION variable e.g.:
# make -f STM32Make.make -j 16  OPTIMIZATION=Os

# variable which determines if it is a debug build
DEBUG ?= 1

# debug flags when debug is defined
OPTIMIZATION ?= -Og

RELEASE_DIRECTORY = $(BUILD_DIRECTORY)/debug
ifeq ($(DEBUG),1)
  # Sets debugging optimization -Og and the debug information output
  OPTIMIZATION_FLAGS += -Og -g -gdwarf -ggdb
  $(TARGET) := $(TARGET)-debug
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/debug
else
  OPTIMIZATION_FLAGS += $(OPTIMIZATION)
  $(TARGET) := $(TARGET)-release
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/release
endif

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/adc.c \
Core/Src/dma.c \
Core/Src/encoder.c \
Core/Src/freertos.c \
Core/Src/gpio.c \
Core/Src/hcsr04.c \
Core/Src/i2c.c \
Core/Src/interrupts.c \
Core/Src/main.c \
Core/Src/motion_control.c \
Core/Src/motor_control.c \
Core/Src/motordriver.c \
Core/Src/servo_control.c \
Core/Src/stm32l4xx_hal_msp.c \
Core/Src/stm32l4xx_hal_timebase_tim.c \
Core/Src/stm32l4xx_it.c \
Core/Src/syscalls.c \
Core/Src/sysmem.c \
Core/Src/system_stm32l4xx.c \
Core/Src/tim.c \
Core/Src/usart.c \
Core/Src/utils.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_exti.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
micro_ros_stm32cubemx_utils/extra_sources/custom_memory_manager.c \
micro_ros_stm32cubemx_utils/extra_sources/microros_allocators.c \
micro_ros_stm32cubemx_utils/extra_sources/microros_time.c \
micro_ros_stm32cubemx_utils/extra_sources/microros_transports/dma_transport.c


CXX_SOURCES = \


# ASM sources
ASM_SOURCES =  \
startup_stm32l452xx.s


#######################################
# Tools
#######################################
ARM_PREFIX = arm-none-eabi-
POSTFIX = "
PREFIX = "
# The gcc compiler bin path can be defined in the make command via ARM_GCC_PATH variable (e.g.: make ARM_GCC_PATH=xxx)
# or it can be added to the PATH environment variable.
# By default the variable be used from the environment file: .stm32env.
# if it is not defined

ifdef ARM_GCC_PATH
    CC = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX)
    CXX = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)g++$(POSTFIX)
    AS = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX) -x assembler-with-cpp
    CP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objcopy$(POSTFIX)
    SZ = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)size$(POSTFIX)
    DP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objdump$(POSTFIX)
else
  CC ?= $(ARM_PREFIX)gcc
  CXX ?= $(ARM_PREFIX)g++$
  AS ?= $(ARM_PREFIX)gcc -x assembler-with-cpp
  CP ?= $(ARM_PREFIX)objcopy
  SZ ?= $(ARM_PREFIX)size
  DP ?= $(ARM_PREFIX)objdump
endif

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
LSS = $(DP) -h -S


REMOVE_DIRECTORY_COMMAND = rm -fR
mkdir_function = mkdir -p $(1)
ifeq ($(OS),Windows_NT)
  convert_to_windows_path = $(strip $(subst /,\,$(patsubst %/,%,$(1))))
  REMOVE_DIRECTORY_COMMAND = cmd /c rd /s /q
  mkdir_function = cmd /e:on /c if not exist $(call convert_to_windows_path,$(1)) md $(call convert_to_windows_path,$(1))
endif


# Flash and debug tools
# Default is openocd however will be gotten from the env file when existing
OPENOCD ?= openocd


#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DRCUTILS_LOG_MIN_SEVERITY=RCUTILS_LOG_MIN_SEVERITY_DEBUG \
-DSTM32L452xx \
-DUSE_FULL_ASSERT \
-DUSE_HAL_DRIVER


# CXX defines
CXX_DEFS =  \
-DSTM32L452xx \
-DUSE_HAL_DRIVER


# AS includes
AS_INCLUDES = \

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/CMSIS/Device/ST/STM32L4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/STM32L4xx_HAL_Driver/Inc \
-IDrivers/STM32L4xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/action_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/action_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/action_msgs/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/action_msgs/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/actionlib_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/actionlib_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/builtin_interfaces/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/builtin_interfaces/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/composition_interfaces/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/composition_interfaces/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/composition_interfaces/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/diagnostic_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/diagnostic_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/diagnostic_msgs/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/diagnostic_msgs/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/example_interfaces/action \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/example_interfaces/action/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/example_interfaces/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/example_interfaces/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/example_interfaces/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/example_interfaces/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/geometry_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/geometry_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/lifecycle_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/lifecycle_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/lifecycle_msgs/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/lifecycle_msgs/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/micro_ros_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/micro_ros_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/micro_ros_utilities \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/mobi_interfaces/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/mobi_interfaces/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/mobi_interfaces/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/mobi_interfaces/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/nav_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/nav_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/nav_msgs/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/nav_msgs/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcl \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcl_action \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcl_interfaces/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcl_interfaces/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcl_interfaces/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcl_interfaces/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcl_lifecycle \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcl_logging_interface \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rclc \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rclc_lifecycle \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rclc_parameter \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcutils \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcutils/stdatomic_helper/gcc \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcutils/stdatomic_helper/win32 \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcutils/testing \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rcutils/types \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rmw \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rmw/events_statuses \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rmw/impl \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rmw/impl/cpp \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rmw_microros \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rmw_microxrcedds_c \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rosgraph_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rosgraph_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rosidl_dynamic_typesupport \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rosidl_dynamic_typesupport/api \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rosidl_runtime_c \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rosidl_runtime_c/type_description \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rosidl_typesupport_c \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rosidl_typesupport_interface \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rosidl_typesupport_introspection_c \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/rosidl_typesupport_microxrcedds_c \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/sensor_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/sensor_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/sensor_msgs/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/sensor_msgs/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/service_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/service_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/shape_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/shape_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/statistics_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/statistics_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/std_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/std_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/std_srvs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/std_srvs/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/std_srvs/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/stereo_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/stereo_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/test_msgs \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/test_msgs/action \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/test_msgs/action/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/test_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/test_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/test_msgs/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/test_msgs/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/tf2_msgs/action \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/tf2_msgs/action/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/tf2_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/tf2_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/tf2_msgs/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/tf2_msgs/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/tracetools \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/trajectory_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/trajectory_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/type_description_interfaces/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/type_description_interfaces/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/type_description_interfaces/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/type_description_interfaces/srv/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/ucdr \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/unique_identifier_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/unique_identifier_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/core/communication \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/core/session \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/core/session/stream \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/core/type \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/profile/discovery \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/profile/multithread \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/profile/transport/can \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/profile/transport/custom \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/profile/transport/ip \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/profile/transport/ip/tcp \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/profile/transport/ip/udp \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/profile/transport/serial \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/profile/transport/stream_framing \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/uxr/client/util \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/visualization_msgs/msg \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/visualization_msgs/msg/detail \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/visualization_msgs/srv \
-Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include/visualization_msgs/srv/detail



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(C_INCLUDES) $(C_DEFS) $(OPTIMIZATION_FLAGS) 

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

CXXFLAGS = $(MCU) $(CXX_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

# Add additional flags
CFLAGS += -Wall -fdata-sections -ffunction-sections 
ASFLAGS += -Wall -fdata-sections -ffunction-sections 
CXXFLAGS += 

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

# Output a list file for the compiled source file.
# This is a representative of the source code in assembly
ASSEMBLER_LIST_OUTPUT_FLAG = -Wa,-a,-ad,-alms=$(call add_release_directory,$<,lst)
CFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)
CXXFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32L452RETxP_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = \


# Additional LD Flags from config file
ADDITIONALLDFLAGS = -Wl,--print-memory-usage -specs=nano.specs -u _printf_float micro_ros_stm32cubemx_utils/microros_static_library/libmicroros/libmicroros.a 

LDFLAGS = $(MCU) $(ADDITIONALLDFLAGS) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIRECTORY)/$(TARGET).map,--cref -Wl,--gc-sections

#######################################
# build the application
#######################################
add_release_directory = $(sort $(addprefix $(RELEASE_DIRECTORY)/,$(addsuffix .$(2),$(basename $(notdir $(1))))))



OBJECTS = $(call add_release_directory,$(C_SOURCES),o)
OBJECTS += $(call add_release_directory,$(CXX_SOURCES),o)
OBJECTS += $(call add_release_directory,$(ASM_SOURCES),o)
vpath %.c $(sort $(dir $(C_SOURCES)))
vpath %.cc $(sort $(dir $(CXX_SOURCES)))
vpath %.cp $(sort $(dir $(CXX_SOURCES)))
vpath %.cxx $(sort $(dir $(CXX_SOURCES)))
vpath %.cpp $(sort $(dir $(CXX_SOURCES)))
vpath %.c++ $(sort $(dir $(CXX_SOURCES)))
vpath %.C $(sort $(dir $(CXX_SOURCES)))
vpath %.CPP $(sort $(dir $(CXX_SOURCES)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
vpath %.S $(sort $(dir $(ASM_SOURCES)))

#######################################
# all
#######################################
# note needs to be located as the first rule to be the default build rule
# default action: build all
all: $(RELEASE_DIRECTORY)/$(TARGET).elf $(RELEASE_DIRECTORY)/$(TARGET).hex $(RELEASE_DIRECTORY)/$(TARGET).bin $(RELEASE_DIRECTORY)/$(TARGET).lss 


# C build
$(RELEASE_DIRECTORY)/%.o: %.c STM32Make.make | $(RELEASE_DIRECTORY)
	$(CC) -c $(CFLAGS) $< -o $@

# C++ build 
$(RELEASE_DIRECTORY)/%.o: %.cc STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cp STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cxx STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cpp STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.c++ STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.C STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.CPP STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

#Assembly build
$(RELEASE_DIRECTORY)/%.o: %.s STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.S STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.sx STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/$(TARGET).elf: $(OBJECTS) STM32Make.make | $(RELEASE_DIRECTORY)
	@echo $(OBJECTS) > $@.in
	$(CC) @$@.in $(LDFLAGS) -o $@
	$(SZ) $@

$(RELEASE_DIRECTORY)/%.hex: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(HEX) $< $@

$(RELEASE_DIRECTORY)/%.bin: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(BIN) $< $@

$(RELEASE_DIRECTORY)/%.lss: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(LSS) $< > $@

$(RELEASE_DIRECTORY):
	$(call mkdir_function, $@)

$(BUILD_DIRECTORY): | $(RELEASE_DIRECTORY)
	$(call mkdir_function, $@)


#######################################
# flash
#######################################
flash: all
	"$(OPENOCD)" -f ./openocd.cfg -c "program $(RELEASE_DIRECTORY)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: all
	"$(OPENOCD)" -f ./openocd.cfg -c "init; reset halt; stm32l4x mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	$(REMOVE_DIRECTORY_COMMAND) $(BUILD_DIRECTORY)

#######################################
# custom makefile rules
#######################################

	
#######################################
# dependencies
#######################################
-include $(wildcard $(RELEASE_DIRECTORY)/*.d)

# *** EOF ***